### ISSUE TITLE
Column-wise vs. Row-wise

### ISSUE THREAD

**Issue by danielkelshaw** [HamzaSardar/PyCoarseNet#7]
From the looks of your implementation it appears that the data for a given variable is accessed along a given row. It would be much more common to see all the data for a given variable in a single column instead.

https://github.com/HamzaSardar/PyCoarseNet/blob/47baebc46cdd1bf1b6ce11ff8abcdabf9e6129fc/pycoarsenet/training/model_setup.py#L36-L37

i.e:

```python
x = data[:, COLUMN]
```

**Comment by HamzaSardar** [comment]
Rows are data points i.e. cell centres, columns are variables. `train_indices` refers to the randomly selected indices from the training validation split.
